-- 코드를 입력하세요
SELECT LEFT(O.SALES_DATE, 4) AS YEAR, MID(O. SALES_DATE, 6, 2) + 0 AS MONTH, U.GENDER AS GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY LEFT(O.SALES_DATE, 4), MID(O. SALES_DATE, 6, 2), U.GENDER
ORDER BY LEFT(O.SALES_DATE, 4), MID(O. SALES_DATE, 6, 2), U.GENDER
