-- 코드를 입력하세요 입양 기록 (ANIMAL_OUTS) O 보호소에 들어온 기록 (ANIMAL_INS) X
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I 
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID