-- 코드를 입력하세요
SELECT A.APNT_NO AS APNTNO, P.PT_NAME AS PTNAME, P.PT_NO AS PTNO, A.MCDP_CD AS MCDPCD, D.DR_NAME AS DRNAME, A.APNT_YMD AS APNTYMD
FROM APPOINTMENT AS A JOIN PATIENT AS P ON A.PT_NO = P.PT_NO JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID 
WHERE A.MCDP_CD = 'CS' AND date_format(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD ASC;